name: movie
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  dio: ^4.0.6
  flutter:
    sdk: flutter
  presentation:
    path: packages/presentation
  data:
    path: packages/data
  cupertino_icons: ^1.0.2
  firebase_core: ^1.24.0
  firebase_auth: ^3.11.1
  firebase_analytics: ^9.3.7
  cloud_firestore: ^3.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - resources/images/
    - resources/flavors_config/
    - secrets.yaml
  uses-material-design: true
  generate: true
