// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxPm7r2vq_ZJ9Uu_8inezSyIxb7K72Fxo',
    appId: '1:310807887827:android:494e7a847f00e6d6e1f926',
    messagingSenderId: '310807887827',
    projectId: 'star-movie-app-10102',
    storageBucket: 'star-movie-app-10102.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDt5GjkQmlnRCts-642_mufXtiGcvlpcyU',
    appId: '1:310807887827:ios:f3c7e3cb9147ced2e1f926',
    messagingSenderId: '310807887827',
    projectId: 'star-movie-app-10102',
    storageBucket: 'star-movie-app-10102.appspot.com',
    androidClientId: '310807887827-qde0fmrrq3ocsbbdd577qcn5hgkg917b.apps.googleusercontent.com',
    iosClientId: '310807887827-e8l0og261pnmfp0uo2l62r45dtcu4tih.apps.googleusercontent.com',
    iosBundleId: 'com.example.movie.prod',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDt5GjkQmlnRCts-642_mufXtiGcvlpcyU',
    appId: '1:310807887827:ios:f3c7e3cb9147ced2e1f926',
    messagingSenderId: '310807887827',
    projectId: 'star-movie-app-10102',
    storageBucket: 'star-movie-app-10102.appspot.com',
    androidClientId: '310807887827-qde0fmrrq3ocsbbdd577qcn5hgkg917b.apps.googleusercontent.com',
    iosClientId: '310807887827-e8l0og261pnmfp0uo2l62r45dtcu4tih.apps.googleusercontent.com',
    iosBundleId: 'com.example.movie.prod',
  );
}
