name: build-on-main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'
          channel: 'stable'
      - run: flutter --version
      - name: Set secrets
        run: |
          touch secrets.yaml
          echo "${{ secrets.PROD_API_KEY }}" >> secrets.yaml;
          echo "${{ secrets.IMG_API_KEY }}" >> secrets.yaml;
          echo "${{ secrets.TMDB_API_KEY }}" >> secrets.yaml;
          echo "${{ secrets.FACEBOOK_APP_ID }}" >> secrets.yaml;
          echo "${{ secrets.FACEBOOK_CLIENT_TOKEN }}" >> secrets.yaml;
          echo "${{ secrets.FB_LOGIN_PROTOCOL_SCHEME }}" >> secrets.yaml;
#      - name: Flutter dependencies
#        run: |
#          flutter pub get
#          cd ./packages/data && flutter pub get
#          cd ./packages/domain && flutter pub get
#          cd ./packages/presentation && flutter pub get
      - name: JsonSerializableGenerator
        run: flutter pub run build_runner build
        working-directory: packages/domain
      - name: Localization generator
        run: flutter gen-l10n
        working-directory: packages/presentation
      - name: Build APK
        run: flutter build apk --release -t lib/main_prod.dart --flavor prod
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          artifacts: "build/app/outputs/flutter-apk/app-prod-release.apk"
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false