name: build-on-pr #sandbox debug

on:
  pull_request:
    types:
      - opened
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'
          channel: 'stable'
      - run: flutter --version
      - name: Set secrets
        run: |
          touch secrets.yaml
          echo "${{ secrets.SANDBOX_API_KEY }}" >> secrets.yaml;
          echo "${{ secrets.IMG_API_KEY }}" >> secrets.yaml;
          echo "${{ secrets.TMDB_API_KEY }}" >> secrets.yaml;
          echo "${{ secrets.FACEBOOK_APP_ID }}" >> secrets.yaml;
          echo "${{ secrets.FACEBOOK_CLIENT_TOKEN }}" >> secrets.yaml;
          echo "${{ secrets.FB_LOGIN_PROTOCOL_SCHEME }}" >> secrets.yaml;
      - name: Flutter dependencies
        run: |
          flutter pub get
          cd ./packages/data && flutter pub get
          cd ./packages/domain && flutter pub get
          cd ./packages/presentation && flutter pub get
      - name: JsonSerializableGenerator
        run: cd ./packages/domain && flutter pub run build_runner build
      - name: Localization generator
        run: cd ./packages/presentation && flutter gen-l10n
      - name: Build APK
        run: flutter build apk --debug -t lib/main_sandbox.dart --flavor sandbox
      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.3.5
        with:
          appId: ${{secrets.FIREBASE_ANDROID_APP_ID}}
          serviceCredentialsFileContent: ${{secrets.CREDENTIAL_FILE_CONTENT}}
          groups: testers
          file: build/app/outputs/flutter-apk/app-sandbox-debug.apk